POST http://localhost:3001/api/orders/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3001/api/orders/ HTTP/1.1

###

DELETE http://localhost:3001/api/orders/deleteall HTTP/1.1

###
GET http://localhost:3001/api/orders/cart/ HTTP/1.1

###
POST http://localhost:3001/api/orders/cart/ HTTP/1.1
Content-Type: application/json

{
    "products": [
        {
            "_id": "62b78733603a26a050eab5b2",
            "amount": 1
        }
    ]
}

###
DELETE http://localhost:3001/api/orders/cart/62b78733603a26a050eab5b2 HTTP/1.1